### PR TITLE
Oh my god (not ready to merge)

### PR DESCRIPTION
**Pull request by baev**
## This change can break some people, so it should be in 1.5

* Split configs. `AllureConfig` - adaptor configuration. `AllureReportConfig` - report configuration.
* Use `nio` instead `io`.
* Merge all the utils into `AllureUtils`. Now it contains all useful methods to use with model.
* Remove `allure-commons` module.
* Generate `index.html` during report generation.

### CODE REVIEW

**Comment by baev** [comment]
retest this please

**Comment by lanwen** [comment]
> Generate index.html during report generation.
what for?

**Comment by just-boris** [comment]
@lanwen client optimization. We want to inject all plugin javascripts directly in the html during the report generation instead of create special file `plugins.json`

**Comment by just-boris** [comment]
Now you see loader while page is loading.
image
This feature allows us to deliver content faster and get rid of that.

**Comment by eroshenkoam** [comment]
lgtm

**Comment by lanwen** [comment]
please rename it :)

**Pull request merged**
