### PR TITLE
Test case title fix

### PR DESCRIPTION
**Pull request by sskorol**
Fixed an issue with title displaying on test cases' table view, when test name was displayed instead of a title (see https://github.com/allure-framework/allure-core/issues/825).

### CODE REVIEW

**Comment by sskorol** [comment]
@just-boris @baev 
```
[ERROR] npm ERR! Linux 3.13.0-61-generic
[ERROR] npm ERR! argv "/home/qatools/workspace/allure-core_pull-request/allure-report-face/node/node" "/home/qatools/workspace/allure-core_pull-request/allure-report-face/node/node_modules/npm/bin/npm-cli.js" "run" "jasmine"
[ERROR] npm ERR! node v5.0.0
[ERROR] npm ERR! npm  v3.5.1
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! allure-report-face@1.0.0 jasmine: `cross-env JASMINE_CONFIG_PATH=jasmine.json DEBUG=allure-face:test jasmine`
```
Anything changed in `npm` dependencies?

**Comment by just-boris** [comment]
The actual error above. You failed the tests:

```
[INFO] 21 specs, 4 failures
[INFO] Finished in 0.771 seconds
```

We have tests on the component, and they had failed after your change.

That's why I'd like to check whether this is expected behavior or not.

**Comment by sskorol** [comment]
@just-boris ok, let me double check test
@baev could you please confirm valid behavior?

**Comment by sskorol** [comment]
@baev @just-boris tests fixed. And here's result:

image

**Comment by baev** [comment]
thanks!

**Pull request merged**
