### PR TITLE
Add TestCaseFailureEvent and TestStepFailureEvent to LifeCycleListner…

### PR DESCRIPTION
**Pull request by lodgvideon**
… instead of TestCaseEvent and TestStepEvent

### CODE REVIEW

**Comment by lanwen** [comment]
what the main purpose of this change? TestCaseEvent can be used to get (of fire) failure event without any problem

**Comment by lodgvideon** [comment]
Yes but TestCaseEvent and TestStep are General event types. And it is not clear to listen TestFailure or TestStepFailure with TestStep and TestCase Events. For me - there can be false positives with this conception.

**Comment by lanwen** [comment]
you can create own listener interface with custom events only and check correct type of event in common listener. It can't be false-positive because of every testcase (teststep) event knows own status.

```java
 @Override
    public void fire(TestCaseEvent event) {
        if(TestCaseFailureEvent.class.isInstance(event)) {
             //your logic
        }
    }
```

**Comment by lodgvideon** [comment]
Of course i can, but for my opinion: if you provide logic to listen events, why you don't provide logic to listen this kind of events in interface?. When i start writing integration, i spent time to look through code and find that TestCaseEvent is what i searched for. Anyway, i think it will be more clear to provide this events in interface. (Also you can just add comment to the TestCaseEvent in the interface.)

**Comment by lanwen** [comment]
This part of allure api is experimental - thats why it has lack of documentation. The main listener class provides all functionality to do any kind of own listener. So it not need to expose all kind of events (its ridiculous to have 30 `fire` methods to any type of event). It's your choice to watch only for specific events. So it should be done in your code only and not in allure.

**Comment by lodgvideon** [comment]
Ok then. Thanks for looking in to this.

**Pull request closed without merging**
