### PR TITLE
Show duration as well as start time for test step

### PR DESCRIPTION
**Pull request by pupssman**
Itial touch on #532 

@baev, @just-boris -- please, have a look

### CODE REVIEW

**Comment by pupssman** [comment]
Or it can be done like this:
duration

**Comment by pupssman** [comment]
Like here: http://ci.qatools.ru/job/allure-core_pull-request/56/artifact/allure-report-preview/target/allure-report/index.html#/home/2673b5c955a1df45/bbc4eb73419945b7

**Comment by baev** [comment]
retest this please

**Comment by pupssman** [comment]
When is the next release?

**Comment by eroshenkoam** [comment]
today

**Pull request merged**
