### PR TITLE
Test cases startup date/time displaying

### PR DESCRIPTION
**Pull request by shimkiv**
It is useful to see the launch date/time of a particular test case

### CODE REVIEW

**Comment by just-boris** [comment]
Screenshot with this feature:
screen shot 2015-05-17 at 17 54 56

@baev your opinion?

**Comment by baev** [comment]
@just-boris I personally don't like it. The header looks overloaded

**Comment by lanwen** [comment]
:-1: agree with @baev

**Comment by just-boris** [comment]
@shimkiv steps have visible start times. Maybe you can use them?
2015-05-18 16-12-57 allure dashboard

Now we already have important information in header such as bug, links, agruments for parametrized tests. This extra information make header enormous.
So, closing issue, because current implementation cannot be merged.

**Comment by shimkiv** [comment]
@just-boris maybe, thanks

**Comment by baev** [comment]
Maybe someone has any other ideas where we can place start/stop time for test case?

**Comment by shimkiv** [comment]
What about the footer ?
snapshot241

**Comment by just-boris** [comment]
Test case start time on the bottom of page... Not so obvious for users.
Earlier we had an idea to put hard-coded steps "Test start" and "Test end" into the list.
Maybe it should to look at this again
2015-05-19 13-42-50 allure dashboard

**Comment by lanwen** [comment]
@just-boris no way!

**Comment by just-boris** [comment]
@lanwen we can put only step about start and show finishing step only if there is no steps with failure. This info can be useful.
And please remind me, why we got rid from it at that time?

**Comment by lanwen** [comment]
@just-boris its overweight info. Timestamp needed only for step to find this action in logs. Case start/stop time tells nothing. It could be viewed in timeline tab if nessesary

**Comment by shimkiv** [comment]
@lanwen it can be useful for those who don't use steps and serves, for example, to find the same info in logs.
IMO: it is not simple task to find out what you're looking for in Timeline report in case if you have a large number of testcases.

**Pull request closed without merging**
