### PR TITLE
Bugfix: exception is now displayed in last failed step when there are multiple failed steps

### PR DESCRIPTION
**Pull request by alkedr**
Related to issue #191 and pull request #352.
Before:

After:

### CODE REVIEW

**Comment by buzdin** [comment]
Probably related to pull request #498, which unlocks the possibility to have multiple failures per test case depending on framework and approach used.

**Comment by alkedr** [comment]
The goal of this pull request was to fix a bug described in #431.
I think it's a bug because current behaviour is not what user would expect.
If you don't want to deal with this issue we need (1) document it somewhere where all users can see it and (2) detect situations when this bug can cause generation of incorrect report and provide good error message.

**Comment by volkovs** [comment]
@buzdin Not exactly. #498 does nothing with exceptions leaving it as is.

**Comment by buzdin** [comment]
One of the reasons to delay merging of this request, as I understand from this thread, is that it is assumed as a best practice to have one failure per test case. The pull requests merged some time ago allows having multiple failures on test step level in a single test case. Which means this bug fix makes sense and Allure needs to show failures exactly at the test step it occurred.

**Comment by alkedr** [comment]
@buzdin Are you talking about #352?

**Comment by baev** [comment]
closed because https://github.com/allure-framework/allure-core/issues/721

**Pull request closed without merging**
