### PR TITLE
Feature - story links

### PR DESCRIPTION
**Pull request by sskorol**
Partial implementation of initial #702 request:
 - updated Stories format to handle Story arrays;
 - updated testcases model with new story entities;
 - added corresponding story handlers into AnnotationManager;
 - fixed broken tests;
 - added stories links support into report face.

Here's how it looks like in report:

image

### CODE REVIEW

**Comment by sskorol** [comment]
@baev I know that it should be implemented in Allure 2, but as we don't have any ETA, would be nice to pick this update into current 1.4.24.RC2.

**Comment by sskorol** [comment]
summon @baev

**Comment by baev** [comment]
@sskorol Hi! Thanks for the contribution! 

You can not change public API in minor version. So I can't merge this

**Comment by sskorol** [comment]
@baev what do you mean by minor version?.. this PR is based on the latest RC2 code. I meant smth like a new RC3 build.

**Comment by baev** [comment]
The reason why we released RC is that we really want to release a new face and give it to people but it breaks old plugin API. So I don't gonna break all java adaptors as well. For now we have thousands of tests marked with the stories annotation. You propose to people to change all the tests? And then, in few months, we gonna change all the adaptors, and people will refactor the tests again

**Comment by sskorol** [comment]
Ok, I see you point. Hope story links will be present in Allure 2 out of the box. Closing this one.

**Comment by baev** [comment]
BTW thanks for all the work

**Comment by sskorol** [comment]
NP, I did it for our own project needs, so it wasn't a waste of time. :)

**Pull request closed without merging**
