### PR TITLE
Support multi testId for one test like issue

### PR DESCRIPTION
**Pull request by wuhuizuo**
example in some one testsuite.xml:
```xml
      <labels>
        <label name="thread" value="13758680"/>
        <label name="host" value="debian-wuhuizuo"/>
        <label name="testId" value="429265"/>
        <label name="testId" value="123456"/>
      </labels>
```
there has two testId labels for the testcase,then the report will display two testId.

### CODE REVIEW

**Comment by wuhuizuo** [comment]
@baev 
why the jenkins ci build fail for merge request:
http://ci.qatools.ru/job/allure-core_pull-request/296/
http://ci.qatools.ru/job/allure-core_pull-request/296/

That seems not my issues.

**Comment by baev** [comment]
@wuhuizuo you also need to update test

http://ci.qatools.ru/job/allure-core_pull-request/ru.yandex.qatools.allure$allure-report-data/296/testReport/junit/ru.yandex.qatools.allure.data/AllureReportGeneratorTest/shouldGenerateWithoutFailures/

**Comment by wuhuizuo** [comment]
@baev unit test is updated.

**Comment by baev** [comment]
@wuhuizuo thanks!

**Pull request merged**
