### PR TITLE
refactor: tabs as independent modules

### PR DESCRIPTION
**Pull request by just-boris**
Step forward to plugins support

### CODE REVIEW

**Comment by just-boris** [comment]
cc @lanwen, @artkoshelev
You can see examples of plugins in `plugins` folder. What do you think about API?

**Comment by artkoshelev** [comment]
ilgtm

**Comment by lanwen** [comment]
The same. In needs to write some plugin to say about usability of api :)

**Comment by just-boris** [comment]
@baev LMTS and go on :balloon:

**Comment by baev** [comment]
Thanks!

**Pull request merged**
