### PR TITLE
Use express-server for development purposes

### PR DESCRIPTION
**Pull request by just-boris**
`jetty-maven-plugin` cannot handle our generated `index.html`. So, we decided to use tiny server on `node.js`. How to use:
* install node.js if still don't
* Generate report data `mvn clean compile -P dev -f allure-report-face/pom.xml`
* Run dev-server `cd allure-report-face/server && npm install && npm start`

### CODE REVIEW

**Comment by just-boris** [comment]
retest this please

**Comment by lanwen** [comment]
please update https://github.com/allure-framework/allure-core/wiki/How-can-I-help after merge

is there any maven plugin to download and run nodejs? :)

**Comment by lanwen** [comment]
https://github.com/skwakman/nodejs-maven-plugin

**Comment by just-boris** [comment]
> please update https://github.com/allure-framework/allure-core/wiki/How-can-I-help after merge

of course

I don't like any downloaders and other wrapper stuff. Properly installed tools is better.
You have a lot of things to make installation easier:
* `brew install node` – my way
* `curl -L http://git.io/n-install | bash` – nice way too

**Comment by lanwen** [comment]
okay

**Comment by baev** [comment]
@just-boris thanks!

**Pull request merged**
