### PR TITLE
use css triming for nice titles

### PR DESCRIPTION
**Pull request by just-boris**
**NOT ready for merge yet**
Here is few caveats such as it always will be in one line. Some people would like to see whole title, even on two strings

### CODE REVIEW

**Comment by just-boris** [comment]
It can be trimmed in [narrow view](http://teamcity.qatools.ru/repository/download/allure_core_pull_request_build/1994:id/index.html#/home/1972ab4fb5992bfa/528ad2b71fc0637) and fully shown in [expanded](http://teamcity.qatools.ru/repository/download/allure_core_pull_request_build/1994:id/index.html#/home/1972ab4fb5992bfa/528ad2b71fc0637/expanded)

**Comment by clicman** [comment]
What about full name on tooltip only?
P.S. I afraid to use CSS due browsers issues.

**Comment by just-boris** [comment]
@clicman of course, title on hover should be here. I've updated my commit.
Browser support: [everywhere](http://caniuse.com/#search=text-overflow)

**Comment by just-boris** [comment]
summon @baev

**Comment by baev** [comment]
IMO we should show full title by click. 

Summon @allure-framework/qatools-team

**Comment by lanwen** [comment]
Think there https://yadi.sk/i/ky-bJUPYekVpe it should be full-length title

**Comment by just-boris** [comment]
@lanwen what's the criteria of trimming do you suggest?

**Comment by lanwen** [comment]
@just-boris special page - full, overview of all - trimming

**Comment by baev** [comment]
closed because https://github.com/allure-framework/allure-core/issues/721

**Pull request closed without merging**
