### PR TITLE
Don't start all suites at run start

### LINKED ISSUE #467: What th meaning of "Duration" field in xUnit tab?
As I can see in example [report](http://teamcity.qatools.ru/repository/download/allure_core_master_release/lastSuccessful/index.html?guest=1#/home) duration is test-after-test incremented time (next duration = all previous tests xexution times plus current) but I suppose it should be durarion for each test only. 
Is this feature or bug? If it it feature, could you explain use cases?

### PR DESCRIPTION
**Pull request by baev**
fixes #467

### CODE REVIEW

**Comment by vania-pooh** [comment]
@baev stop fucking around and merge this fucking fuck.

**Comment by clicman** [comment]
Also you should remove testRunFinished override method and modify testFinished:

```java
    @Override
    public void testFinished(Description description) {
        if (description.isSuite()) {
            testSuiteFinished(getSuiteUid(description));
        } else {
            getLifecycle().fire(new TestCaseFinishedEvent());
        }
    }
```

Also tests must be changed according tis changes. After all duration calculates well.

**Comment by baev** [comment]
@clicman thanks for proposing but raw JUnit4 don't provide `testFinished` event for suites..

**Comment by clicman** [comment]
@baev Could you explain this your point?
As I know it is from default JUnit api and all descriptions are managed via testStartrd/testFinished - suites and tests. Or I something missed?

**Comment by baev** [comment]
Nope, you can check it:

```java
public class SimpleTestClass {
    @Test
    public void passedTest() throws Exception {
    }
}

...

JUnitCore core = new JUnitCore();
core.addListener(new RunListener() {
    @Override
    public void testFinished(Description description) throws Exception {
        System.out.println(description.getDisplayName());
    }
});
core.run(SimpleTestClass.class);
```

**Comment by clicman** [comment]
What about some custom [notifier](https://gist.github.com/clicman/2e74e47f464b19fbbc12)?
Result as expected:
```
Start Suite:NewTestSuite
Start test:testMain(TestSampleTest)
Finish test:testMain(TestSampleTest)
Finish Suite:NewTestSuite
```

**Comment by baev** [comment]
@clicman interesting

How to specify custom runNotifier when run tests using *maven-surefire-plugin*?

**Comment by clicman** [comment]
@baev I think it can be initialized in listener and assigned to "this" object like
```java
notifier.addListener(this);
```
Or create notifier in listener what adds another listener :)

Additional research needed to answer your question.

**Comment by baev** [comment]
@clicman I'll think about it. Thanks!

**Pull request merged**
