### PR TITLE
Allow "Features" to be inherited (#874)

### PR DESCRIPTION
**Pull request by afelisatti**

### CODE REVIEW

**Comment by baev** [comment]
it is makes sense to make other annotations inherited as well

**Comment by afelisatti** [comment]
Which ones do you suggest? Features was the most obvious to me since a feature will most likely have several tests associated to it sharing a class hierarchy.

**Comment by baev** [comment]
> Which ones do you suggest? Features was the most obvious to me since a feature will most likely have several tests associated to it sharing a class hierarchy.

All of them

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@afelisatti thanks!

**Comment by afelisatti** [comment]
No problem!

**Comment by baev** [comment]
we decided to add a few more fixes to 1.5.3, so release bit delayed. Working on this right now

**Pull request merged**
