### PR TITLE
Adding test case id annotation (#470)

### PR DESCRIPTION
**Pull request by volkovs**

### CODE REVIEW

**Comment by baev** [comment]
LGTM

**Comment by baev** [comment]
@volkovs thanks for contribution!

**Comment by serhatbolsu** [comment]
I could not make the patter work with 1.4.6. I have allure-properties file in project folder. Along with this I also tried allure.issues.tracker.pattern, that does not work too. I am using maven - testng combination. Is there another way to give this pattern ( like inside maven ) . 
Thank you

**Comment by volkovs** [comment]
Yep, had the same issues. Unfortunately allure-jenkins-plugin 2.5 doesn't include https://github.com/allure-framework/allure-jenkins-plugin/pull/39 configuring patterns. If you generate via maven you can pass JVM argument, e.g. 

mvn clean test site -Dallure.issues.tracker.pattern="http://tms/%s"

If you generate via Jenkins, you have either wait (and push) for the next plugin version, or you can start Jenkins with the same JVM argument (passing it via maven command won't work, since maven tasks and Jenkins plugins are working in separate JVMs).

**Pull request merged**
