### PR TITLE
Replacing of calls of ListenersNotifier fire method

### PR DESCRIPTION
**Pull request by dimand58**
<b>Usage (example):</b>
This feature allow to attach of screenshot(or file, ..., etc) automatically <b>inside</b> step/test/suite after it finished. May be helpful in large projects with high amount of steps/tests.

No necessary add of attaching methods to the end of steps/tests code manually - just use custom LifecycleListener with calling of attaching methods in "public void fire(StepFinishedEvent event)" (example)

<b>WITHOUT this changing all attachments will be added AFTER step/test, not inside of it!</b>

### CODE REVIEW

**Comment by lanwen** [comment]
In this case other listeners will recieve finished event before it actually was. Think it should be same as rules in junit mechanism in future. Don't think this PR could be merged now

**Comment by dimand58** [comment]
Sadness =(
I hope someone can create correct mechanism in near future

**Comment by dimand58** [comment]
@lanwen What do you think about using of some property for calling notifier.fire(event); in the start or end of fire events ?
Sounds like temporary solution, but it is better then nothing...

**Comment by lanwen** [comment]
summon @baev

**Comment by baev** [comment]
> Think it should be same as rules in junit mechanism in future

IMO there are two different types of notifying mechanism: listeners and rules. Listeners can not change current flow but rules can. Using rules you can remove redundant steps, add attachments etc. But using listeners you can only get some information and use it as you wish. 

> This feature allow to attach of screenshot(or file, ..., etc) automatically inside step/test/suite after it finished.

I think we must have two different methods before event and after. But we need to copy events before give it to listeners.

**Comment by dimand58** [comment]
I'm ready to help. Can you show me the way for start? (architecture of feature , basic principles, etc.)

**Comment by baev** [comment]
@dimand58 nice. Give me time to think a little

**Comment by connerT** [comment]
As a new user of Allure I am really impressed with it. This would be a great feature.

**Comment by baev** [comment]
@dimand58 sorry for log delay. Some thoughts: 

1) We should copy all objects before provide it to listeners. 
2) I doubt that allure events is useful in listener. Maybe better to provide context? An example when a step has finished provide `Step` object instead `StepFinishEvent`
3) Maybe we should not add `before` and `after` fixtures for all events (an example - provide `after` fixture for all *start* events and `before` for *finish* events) maybe not. 

How other ppl going to use this listeners?

**Comment by dimand58** [comment]
@baev sorry for delay too. I have no idea at present moment...

**Comment by baev** [comment]
I would not like to merge it as long as listener can change events

**Comment by dimand58** [comment]
@baev How about to creating Step/Test event object clone in "fire" methods in ListenersNotifier class and sending this clone to listeners ?
In this case any listeners can get necessary event info, but can not to affect original event.

**Comment by baev** [comment]
lets move the discussion to https://github.com/allure-framework/allure-core/issues/735

**Pull request closed without merging**
