### PR TITLE
add chinese translation

### PR DESCRIPTION
**Pull request by wuhuizuo**

### CODE REVIEW

**Comment by baev** [comment]
@wuhuizuo thanks!

**Comment by baev** [comment]
@wuhuizuo do you mind to contribute chinese translation to Allure 2?

**Comment by wuhuizuo** [comment]
@baev  I'm glad to

**Comment by baev** [comment]
Nice. 

The main translation file https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/javascript/translations/en.json

also some plugins have translations as well

https://github.com/allure-framework/allure2/blob/master/plugins/behaviors-plugin/src/dist/static/index.js#L3-L15

https://github.com/allure-framework/allure2/blob/master/plugins/packages-plugin/src/dist/static/index.js#L3-L9

**Pull request merged**
