### PR TITLE
CSV attachment viewer (#438)

### PR DESCRIPTION
**Pull request by VikomiC**
CSV attachment viewer (#438)
image

### CODE REVIEW

**Comment by just-boris** [comment]
Amazing! :+1:

**Comment by baev** [comment]
@just-boris in case `;`-separated (Russian Microsoft Excel) csv attachment looks shitty. This question about it http://stackoverflow.com/questions/29313608/csv-preview-messed-up

As I know we can configure separator in `d3.js` but how we can now which one we should use? Maybe other `MIME`-type (an example `dcv`)?

**Comment by baev** [comment]
for more inforamtion see ru.wikipedia.org/wiki/CSV

**Comment by just-boris** [comment]
@baev How we can distinguish used separator?

**Comment by volkovs** [comment]
Mime types support additional parameters like charset, header (https://tools.ietf.org/html/rfc4180#page-4). But that might be overkill. IMO it would be enough to support tab / semicolon separated values via imaginary mime types.

**Comment by just-boris** [comment]
@volkovs I argee. If we want to support more formats, we should add more known mime-types, then it's possible to pass custom separator into d3: https://github.com/mbostock/d3/wiki/CSV#arbitrary-delimiters

**Pull request merged**
