### PR TITLE
Making test step statuses more visible

### PR DESCRIPTION
**Pull request by volkovs**
@baev @just-boris 
Please review if this pull request makes sense.

P.S. However I like unaligned icons variant more

### CODE REVIEW

**Comment by just-boris** [comment]
Looks weird:
image

Failed steps already has highlight corresponding its status. Otherwise step has got status "passed". Why are you need additional icon for it?

**Comment by volkovs** [comment]
Yes, you are right, font color changes. But we wanted to make failed/broken test steps more visible. For reasons behind please come at chat room at https://gitter.im/.

**Comment by volkovs** [comment]
@just-boris Now status icon is displayed only for failed test steps ['FAILED', 'BROKEN', 'CANCELED', 'PENDING']

**Comment by just-boris** [comment]
I talked about this method: https://github.com/allure-framework/allure-core/blob/master/allure-report-face/src/main/webapp/js/testcase/testcase.js#L105
It does the same thing, and better to keep logic in one place

**Comment by volkovs** [comment]
@just-boris I have no experience with AngularJS. I had to redefine isFailed() function in controller scope. Is it correct?

**Comment by just-boris** [comment]
@volkovs code is good.
But why are you added whitespace after sign?

image

**Comment by volkovs** [comment]
@just-boris that is standard Allure position for attachment icons, so everything is aligned (please see screenshot):
image

Since attachments are not so often and passed step icon is not shown any more, probably it will be better to align to the right. I will update the PR.

**Comment by volkovs** [comment]
@just-boris Done

**Comment by volkovs** [comment]
@just-boris TeamCity accidentally fails with message:
"Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.1.0.v20131115:run (start-jetty) on project allure-e2e: Failure"

**Comment by baev** [comment]
@volkovs fixed

**Comment by vania-pooh** [comment]
Looks good.

**Comment by baev** [comment]
@volkovs thanks!

**Pull request merged**
