### PR TITLE
Allow multiline in Defects widget

### PR DESCRIPTION
**Pull request by dimand58**
In some case will be nice to see multiline defect description in Defects widget.
This commit very small and safe)

### CODE REVIEW

**Comment by just-boris** [comment]
Before:
image

After:
image


Maybe it is a good change

**Comment by lanwen** [comment]
:+1: for me

**Comment by vania-pooh** [comment]
Let's merge then.

**Comment by dimand58** [comment]
@vania-pooh , @just-boris hi!
I don't see this change in Allure 1.4.23 . It was missed or removed for some reason ?

**Comment by just-boris** [comment]
We made a full redesign of all frontend during last half year. 

Update is now available as Allure 1.4.24.RC2. There are a lot of differences in look, so maybe you don't need that change anymore. If it is still needs to be done, we have to do it once again, unfortunately.

**Comment by dimand58** [comment]
@just-boris, @baev hi.
1.4.24 looks good, but didn't has multiline feature in Defects tabs =(

**Pull request merged**
